---
- name: add erlang apt key
  apt_key:
    url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc

- name: add erlang apt repository
  apt_repository:
    filename: erlang
    repo: deb http://packages.erlang-solutions.com/debian/ {{ ansible_distribution_release }} contrib

- name: add rabbitmq apt key
  apt_key:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey

- name: add rabbitmq apt repository
  apt_repository:
    filename: rabbitmq-server
    repo: deb https://packagecloud.io/rabbitmq/rabbitmq-server/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} main

- name: install erlang and rabbitmq packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ rabbitmq_erlang_package_name if rabbitmq_erlang_package_name else 'erlang-nox' }}"
    - "{{ 'rabbitmq-server=' + rabbitmq_package_version + '-*' if rabbitmq_package_version else 'rabbitmq-server' }}"
