---
- name: add erlang yum repository
  yum_repository:
    name: erlang
    description: Erlang Solutions Repository
    baseurl: http://packages.erlang-solutions.com/rpm/centos/{{ ansible_distribution_major_version }}/$basearch
    gpgkey: http://packages.erlang-solutions.com/debian/erlang_solutions.asc
    gpgcheck: no

- name: add rabbitmq yum repository
  yum_repository:
    name: rabbitmq-server
    description: RabbitMQ Repository
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/{{ ansible_distribution_major_version }}/$basearch
    gpgkey: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    gpgcheck: no
    repo_gpgcheck: yes

- name: install erlang and rabbitmq packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ rabbitmq_erlang_package | default('erlang') }}"
    - "{{ 'rabbitmq-server' + rabbitmq_package_version if rabbitmq_package_version else 'rabbitmq-server' }}"
